version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./api/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
